### ISSUE TITLE
HabitatSampler_v02, example for the readOGR("...")

### ISSUE THREAD

**Issue by romulogoncalves** [carstennh/HabitatSampler#4]
In the [HabitatSampler_v02.r](https://github.com/carstennh/HabitatSampler/blob/0234c74cb58285d127de5543e45daeab13ebda42/HabitatSampler_v2.0/HabitatSampler_v02.r#L54) script the user needs to provide a shapefile (if we understood it correctly). Would it be possible to have an example so the script is self-contained?

**Comment by carstennh** [comment]
Hi Romulo,
all the data needed to run the example script HabitatSamplr_v02.r are given in the Data folder. The cut<-readOGR(..) function is just an example for the user who wants to clip his/her study area. Since the study area is already clipped for the example script, there is no need to add a specific shapefile her. 
Greetings
Carsten

**Comment by romulogoncalves** [comment]
Now I understand how it works.
