### ISSUE TITLE
Code in R-Package is not identical as the one in HabitatSampler-v2.0

### ISSUE THREAD

**Issue by romulogoncalves** [carstennh/HabitatSampler#9]
The following files differ:
- [x] inner_procedure.r
- [x] outer_procedure.r
- [x] plot_interactive.r
- [x] plot_results.r

**Comment by romulogoncalves** [comment]
@carstennh to see the difference between the files you can use `vimdiff`.
For example,  for the file `inner_procedure.r` just do:
```bash
$ cd HabitatSampler_v2.0/Funktionen/
$ vimdiff inner_procedure.r ../../R-package/R/inner_procedure.r
```

**Comment by romulogoncalves** [comment]
You can add your changes to branch `converge_code`. To do that checkout the latest version of the repository:
```bash
git checkout master
git pull
```
Then move to the branch `converge_code`:
```bash
git checkout converge_code
```

Now you can do all the changes you want without breaking what we have in the master branch.

**Comment by carstennh** [comment]
The differences are because of the two types of code execution. If you use code within an R package you do not need to call libraries since they are already opened in the package framework. So we have two types of code because of two types of execution modes. We need to move the "require()" functions into the master script HabitatSampler_v02.r and remove additional comments.

**Comment by carstennh** [comment]
I will do the necessary code work in the converge_code branch now.

**Comment by romulogoncalves** [comment]
covered by #11
